filters:
- cache_seconds: 600
  pattern: https://www.guancha.cn/*/*.shtml
  selectors:
  - div.content > div > ul
- pattern: https://blog.csdn.net/*/article/details/*
  selectors:
  - main > div.blog-content-box
- pattern: https://x.com/*/status/*
  selectors:
  - //article/ancestor::div[4]
- pattern: https://tree-sitter.github.io/tree-sitter/*
  selectors:
  - div.page
- pattern: https://aider.chat/docs/*
  selectors:
  - div.main-content-wrap
- pattern: https://tree-sitter.github.io/*
  selectors:
  - div.page
