filters:
- cache_seconds: 600
  selectors:
  - div.content > div > ul
  url: https://www.guancha.cn/*/*.shtml
- selectors:
  - main > div.blog-content-box
  url: https://blog.csdn.net/*/article/details/*
- selectors:
  - //article/ancestor::div[4]
  url: https://x.com/*/status/*
- selectors:
  - div.page
  url: https://tree-sitter.github.io/tree-sitter/*
