
- url: https://www.guancha.cn/*/*.shtml
  cache_seconds: 600
  selectors:
    - "div.content > div > ul"


- url: https://blog.csdn.net/*/article/details/*
  selectors:
    - "main > div.blog-content-box"


- url: https://x.com/*/status/*
  selectors:
    - "//article/ancestor::div[4]"

