filters:
- cache_seconds: 600
  selectors:
  - div.content > div > ul
  pattern: https://www.guancha.cn/*/*.shtml
- selectors:
  - main > div.blog-content-box
  pattern: https://blog.csdn.net/*/article/details/*
- selectors:
  - //article/ancestor::div[4]
  pattern: https://x.com/*/status/*
- pattern: https://tree-sitter.github.io/tree-sitter/*
  selectors:
  - div.page
  pattern: https://tree-sitter.github.io/tree-sitter/*
